schema_analysis_task:
  description: >
    For the question: "{question}"
    
    Search for the move_type table using search_table_metadata tool.
    
    Report ONLY these facts:
    - Table name: move_type
    - Columns found
    - Row count
    
    DO NOT write SQL. DO NOT analyze data. Just report what exists.
  expected_output: >
    Table found: [name]
    Columns: [list of column names]
    Row count: [number]
  agent: schema_analyst

business_context_task:
  description: >
    For the question: "{question}"
    
    Search for business terms like "volume" or "move type".
    
    Define ONLY:
    - What "volume" means in this context
    - Any business rules about filtering or grouping
    
    DO NOT list actual move types or percentages.
  expected_output: >
    Term definitions:
    - Volume: [definition]
    - Business rules: [any filtering rules]
  agent: business_context_agent

query_building_task:
  description: >
    Using the table info and business rules from other agents,
    write a SQL query for: "{question}"
    
    Requirements:
    - Use only the table and columns reported by Schema Analyst
    - Apply business rules from Business Context Agent
    - Include comments explaining the query
    
    DO NOT include sample results or made-up data.
  expected_output: >
    ```sql
    -- SQL query with comments
    SELECT ...
    FROM ...
    WHERE ...
    ORDER BY ...
    LIMIT ...
    ```
    
    Brief explanation of what the query does.
  agent: query_builder

query_execution_task:
  description: >
    Execute the EXACT SQL query from the Query Builder using AWS Athena.
    
    CRITICAL Requirements:
    - Copy the SQL query EXACTLY as written by the Query Builder
    - DO NOT modify, improve, or change the query in any way
    - Use database: ams_mns_ai_curated_dev
    - Use the execute_athena_query tool with the exact query
    
    If the query fails, report the error but DO NOT retry with modifications.
  expected_output: >
    Query Results:
    [Actual results from Athena or error message]
    
    Summary: X rows returned (or error details)
  agent: athena_executor