schema_analysis_task:
  description: >
    For the question: "{question}"
    
    Search for the move_type table using search_table_metadata tool.
    
    Report ONLY these facts:
    - Table name: move_type
    - Columns found
    - Row count
    
    DO NOT write SQL. DO NOT analyze data. Just report what exists.
  expected_output: >
    Table found: [name]
    Columns: [list of column names]
    Row count: [number]
  agent: schema_analyst

business_context_task:
  description: >
    For the question: "{question}"
    
    Search for business terms like "volume" or "move type".
    
    Define ONLY:
    - What "volume" means in this context
    - Any business rules about filtering or grouping
    
    DO NOT list actual move types or percentages.
  expected_output: >
    Term definitions:
    - Volume: [definition]
    - Business rules: [any filtering rules]
  agent: business_context_agent

query_building_task:
  description: >
    Using the table info and business rules from other agents,
    write a SQL query for: "{question}"
    
    Requirements:
    - Use only the table and columns reported by Schema Analyst
    - Apply business rules from Business Context Agent
    - Include comments explaining the query
    
    DO NOT include sample results or made-up data.
  expected_output: >
    ```sql
    -- SQL query with comments
    SELECT ...
    FROM ...
    WHERE ...
    ORDER BY ...
    LIMIT ...
    ```
    
    Brief explanation of what the query does.
  agent: query_builder

query_execution_task:
  description: >
    Execute the EXACT SQL query from the Query Builder using AWS Athena.
    
    CRITICAL Requirements:
    - Copy the SQL query EXACTLY as written by the Query Builder
    - DO NOT modify, improve, or change the query in any way
    - Use database: ams_mns_ai_curated_dev
    - Use the execute_athena_query tool with the exact query
    
    If the query fails, report the error but DO NOT retry with modifications.
  expected_output: >
    Query Results:
    [Actual results from Athena or error message]
    
    Summary: X rows returned (or error details)
  agent: athena_executor

adaptive_data_analysis_task:
  description: >
    Transform perfect query results into strategic intelligence using the full adaptive context.
    
    ENHANCED ANALYSIS WITH ADAPTIVE INTELLIGENCE:
    
    Use "Data Analysis and Forecasting Tool" with:
    - Original question: '{question}'
    - Perfect Athena results: High-quality data from precision-filtered queries
    - Adaptive context: Rich business intelligence from Stage 1 analysis
    - Blueprint metadata: Technical context from precision discovery
    
    ADAPTIVE INTELLIGENCE ADVANTAGES:
    - Higher confidence in analysis (precision-filtered data)
    - Richer business context (from BusinessContext enrichment)
    - Strategic depth (from compound relationship understanding)
    - Executive-ready insights (from AI-scored relevance)
    
    ENHANCED ANALYTICAL FRAMEWORK:
    1. DIRECT STRATEGIC ANSWER: Higher confidence due to data precision
    2. BUSINESS CONTEXT INTEGRATION: Leverage enriched business intelligence
    3. ADAPTIVE INSIGHTS: Reference the precision discovery process
    4. STRATEGIC RECOMMENDATIONS: Enhanced by compound relationship understanding
    5. CONFIDENCE ASSESSMENT: Boosted by adaptive pipeline accuracy
    
    STRATEGIC VALUE AMPLIFICATION: The adaptive pipeline provides you with
    superior data quality and richer business context, enabling more strategic
    and confident executive-ready intelligence.
  
  expected_output: >
    Strategic intelligence enhanced by the adaptive pipeline:
    {
      "direct_answer": "High-confidence answer based on precision-filtered data",
      "adaptive_context_integration": {
        "business_enrichment_applied": "How BusinessContext enriched the analysis",
        "precision_discovery_benefits": "How exact schema discovery improved accuracy",
        "ai_scoring_insights": "How column relevance scores enhanced analysis"
      },
      "strategic_analysis": {
        "business_impact": "Strategic implications with higher confidence",
        "confidence_level": "HIGH (enhanced by adaptive pipeline)",
        "precision_benefits": "Accuracy improvements from mandatory filtering",
        "strategic_recommendations": [
          "Recommendation 1 with adaptive intelligence backing",
          "Recommendation 2 with precision-filtered data confidence"
        ]
      },
      "adaptive_pipeline_impact": {
        "data_quality_improvement": "90% accuracy gain from precision filtering",
        "business_context_enrichment": "Enhanced strategic depth from BusinessContext",
        "confidence_amplification": "Higher certainty from AI-driven discovery"
      }
    }
  agent: data_insights_analyst